/*
 * jQuery Easing v1.1 - http://gsgd.co.uk/sandbox/jquery.easing.php
 *
 * Uses the built in easing capabilities added in jQuery 1.1
 * to offer multiple easing options
 *
 * Copyright (c) 2007 George Smith
 * Licensed under the MIT License:
 *   http://www.opensource.org/licenses/mit-license.php
 */jQuery.easing={easein:function(e,t,n,r,i){return r*(t/=i)*t+n},easeinout:function(e,t,n,r,i){if(t<i/2)return 2*r*t*t/(i*i)+n;var s=t-i/2;return-2*r*s*s/(i*i)+2*r*s/i+r/2+n},easeout:function(e,t,n,r,i){return-r*t*t/(i*i)+2*r*t/i+n},expoin:function(e,t,n,r,i){var s=1;if(r<0){s*=-1;r*=-1}return s*Math.exp(Math.log(r)/i*t)+n},expoout:function(e,t,n,r,i){var s=1;if(r<0){s*=-1;r*=-1}return s*(-Math.exp(-Math.log(r)/i*(t-i))+r+1)+n},expoinout:function(e,t,n,r,i){var s=1;if(r<0){s*=-1;r*=-1}return t<i/2?s*Math.exp(Math.log(r/2)/(i/2)*t)+n:s*(-Math.exp(-2*Math.log(r/2)/i*(t-i))+r+1)+n},bouncein:function(e,t,n,r,i){return r-jQuery.easing.bounceout(e,i-t,0,r,i)+n},bounceout:function(e,t,n,r,i){return(t/=i)<1/2.75?r*7.5625*t*t+n:t<2/2.75?r*(7.5625*(t-=1.5/2.75)*t+.75)+n:t<2.5/2.75?r*(7.5625*(t-=2.25/2.75)*t+.9375)+n:r*(7.5625*(t-=2.625/2.75)*t+.984375)+n},bounceinout:function(e,t,n,r,i){return t<i/2?jQuery.easing.bouncein(e,t*2,0,r,i)*.5+n:jQuery.easing.bounceout(e,t*2-i,0,r,i)*.5+r*.5+n},elasin:function(e,t,n,r,i){var s=1.70158,o=0,u=r;if(t==0)return n;if((t/=i)==1)return n+r;o||(o=i*.3);if(u<Math.abs(r)){u=r;var s=o/4}else var s=o/(2*Math.PI)*Math.asin(r/u);return-(u*Math.pow(2,10*(t-=1))*Math.sin((t*i-s)*2*Math.PI/o))+n},elasout:function(e,t,n,r,i){var s=1.70158,o=0,u=r;if(t==0)return n;if((t/=i)==1)return n+r;o||(o=i*.3);if(u<Math.abs(r)){u=r;var s=o/4}else var s=o/(2*Math.PI)*Math.asin(r/u);return u*Math.pow(2,-10*t)*Math.sin((t*i-s)*2*Math.PI/o)+r+n},elasinout:function(e,t,n,r,i){var s=1.70158,o=0,u=r;if(t==0)return n;if((t/=i/2)==2)return n+r;o||(o=i*.3*1.5);if(u<Math.abs(r)){u=r;var s=o/4}else var s=o/(2*Math.PI)*Math.asin(r/u);return t<1?-0.5*u*Math.pow(2,10*(t-=1))*Math.sin((t*i-s)*2*Math.PI/o)+n:u*Math.pow(2,-10*(t-=1))*Math.sin((t*i-s)*2*Math.PI/o)*.5+r+n},backin:function(e,t,n,r,i){var s=1.70158;return r*(t/=i)*t*((s+1)*t-s)+n},backout:function(e,t,n,r,i){var s=1.70158;return r*((t=t/i-1)*t*((s+1)*t+s)+1)+n},backinout:function(e,t,n,r,i){var s=1.70158;return(t/=i/2)<1?r/2*t*t*(((s*=1.525)+1)*t-s)+n:r/2*((t-=2)*t*(((s*=1.525)+1)*t+s)+2)+n},linear:function(e,t,n,r,i){return r*t/i+n}};