// Generated by CoffeeScript 1.6.2
/*
Sticky Elements Shortcut for jQuery Waypoints - v2.0.3
Copyright (c) 2011-2013 Caleb Troughton
Dual licensed under the MIT license and GPL license.
https://github.com/imakewebthings/jquery-waypoints/blob/master/licenses.txt
*/(function(){(function(e,t){return typeof define=="function"&&define.amd?define(["jquery","waypoints"],t):t(e.jQuery)})(this,function(e){var t,n;t={wrapper:'<div class="sticky-wrapper" />',stuckClass:"stuck"};n=function(e,t){e.wrap(t.wrapper);return e.parent()};e.waypoints("extendFn","sticky",function(r){var i,o,u;o=e.extend({},e.fn.waypoint.defaults,t,r);i=n(this,o);u=o.handler;o.handler=function(t){var n,r;n=e(this).children(":first");r=t==="down"||t==="right";n.toggleClass(o.stuckClass,r);i.height(r?n.outerHeight():"");if(u!=null)return u.call(this,t)};i.waypoint(o);return this.data("stuckClass",o.stuckClass)});return e.waypoints("extendFn","unsticky",function(){this.parent().waypoint("destroy");this.unwrap();return this.removeClass(this.data("stuckClass"))})})}).call(this);